/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:453c0f82-660e-4a33-83e3-58ee2760efd0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_v9WMj9KdS",
    "aws_user_pools_web_client_id": "4qbumndt39ct8d8t2aajlll0vi",
    "oauth": {
        "domain": "stayfit3a4fa9fe-3a4fa9fe-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],

        "redirectSignIn": "https://main.d3v2r6evut82hv.amplifyapp.com/",
        "redirectSignOut": "https://main.d3v2r6evut82hv.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "Google"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "stayfit4f3287b86cd64abeb7b8d762303f15ee9024d-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
